### ISSUE TITLE
Errore codice IPA non valido

### ISSUE THREAD

**Issue by trinko** [italia/spid-compliant-certificates-python#147]
Salve,

segnalo che effettuando la validazione ottengo il seguente errore sul codice IPA:
"SPID Compliant Certificates Value for name attribute [Unknown OID, 2.5.4.97] must match ^PA:IT-\S{1,11}$"

Ma il codice IPA della mia scuola è più lungo di 11 caratteri (credo sia così per tutte le scuole): **istsc_catf04000p**

Il codice IPA in questione è ovviamente corretto: [pagina consultazione IPA](https://indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente/scheda-ente/14402)

Se serve, posso allegare l'XML con i metadati completi.

**Comment by peppelinux** [comment]
Please provide a PR to extend this REGEXP if you can, consider me available for a revision and a merge

https://github.com/italia/spid-compliant-certificates-python/blob/199c2e5ebc025a1414c4a52601bcf4734f09cf72/spid_compliant_certificates/validator/checks/subject_dn.py#L55

**Comment by peppelinux** [comment]
@trinko do you see any misalignment with Agid avviso 29v3?

https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati.pdf

**Comment by peppelinux** [comment]
I read

````
In base al §5.1.4 punto 3 della suddetta norma, valorizzato con il prefisso
‘PA:IT-’ seguito dal codice IPA dell’Ente — ad esempio, per il Comune di Roma (codice
IPA ‘c_h501’) tale estensione è valorizzata come “PA:IT-c_h501”
````
then the PR should change the regex to `PUB_SECTOR_PATTERN = r'^PA:IT-\S{1,16}$'`

if you want to do that, then we can do a release together

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/spid-compliant-certificates-python/releases/tag/v0.5.5
