### ISSUE TITLE
Validator report in json format

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-compliant-certificates-python#21]
Actually we have the following behaviour

````
spid-compliant-certificates validator --crt-file src/spid_sp_test/idp/public.cert 
...

[INFO ] Validating certificate src/spid_sp_test/idp/public.cert against public sector specifications
[INFO ] Checking the key type and size: success
[INFO ]     The keypair must be RSA
[INFO ]     The key size must be greater than or equal to 2048 (now: 2048)
[INFO ]     The key size must be one of [2048, 3072, 4096] (now: 2048)
[INFO ] Checking the signature digest algorithm: success
[INFO ]     The digest algorithm must be one of ['sha256', 'sha512'] (now: sha256)
[ERROR] Checking the SubjectDN: failure
[INFO ]     Name attribute [{attr._name}, {attr.dotted_string}] is not allowed in subjectDN
[INFO ]     Name attribute [{attr._name}, {attr.dotted_string}] is not allowed in subjectDN
[INFO ]     Name attribute [{attr._name}, {attr.dotted_string}] is not allowed in subjectDN
[INFO ]     Name attribute [{attr._name}, {attr.dotted_string}] is not allowed in subjectDN
[INFO ]     Name attribute [{attr._name}, {attr.dotted_string}] is not allowed in subjectDN
[INFO ]     Name attribute [{attr._name}, {attr.dotted_string}] is not allowed in subjectDN
[ERROR]     Name attribute [organizationIdentifier, 2.5.4.97] must be present in subjectDN
[ERROR]     Name attribute [uri, 2.5.4.83] must be present in subjectDN
[INFO ]     Name attribute [commonName, 2.5.4.3] must be present in subjectDN
[INFO ]     Name attribute [countryName, 2.5.4.6] must be present in subjectDN
[INFO ]     Name attribute [localityName, 2.5.4.7] must be present in subjectDN
[INFO ]     Name attribute [localityName, 2.5.4.7] must be present in subjectDN
[INFO ]     Name attribute [organizationName, 2.5.4.10] must be present in subjectDN
[INFO ]     Value for name attribute [countryName, 2.5.4.6] can not be empty
[INFO ]     Value for name attribute [countryName, 2.5.4.6] is not a valid country code (IT)
[INFO ]     Value for name attribute [stateOrProvinceName, 2.5.4.8] can not be empty
[INFO ]     Value for name attribute [localityName, 2.5.4.7] can not be empty
[INFO ]     Value for name attribute [organizationName, 2.5.4.10] can not be empty
[INFO ]     Value for name attribute [organizationalUnitName, 2.5.4.11] can not be empty
[INFO ]     Value for name attribute [commonName, 2.5.4.3] can not be empty
[ERROR] Checking basicConstraints x509 extension: failure
[INFO ]     basicConstraints can not be set as critical
[ERROR]     CA must be FALSE
[ERROR] Checking keyUsage x509 extension: failure
[ERROR]     keyUsage must be present
[ERROR] Checking certificatePolicies x509 extension: failure
[ERROR]     certificatePolicies must be present
[ERROR] The certificate src/spid_sp_test/idp/public.cert does not match public sector specifications
````

That's awesome but probably there woudl also the need to have a report in a json format.
This could be implemented here:
https://github.com/italia/spid-compliant-certificates-python/blob/ba7209f889252503e2f182ba2007880ee26004a1/spid_compliant_certificates/validator/validate.py#L40

instead of log the message in stdout we could handle it with an abstract Report class that would be initialized with the argparse option. 

At the same way we could define many python logger handlers and select one of them using argparse CLI. Does this fit to you?

**Comment by psmiraglia** [comment]
Sounds good. My proposal is to structure the JSON report in three levels like in the following. What do you think about that?

**Level 0**

- Global validation result stored in `result` keyword. It accepts only `success` and `failure` values.
- Details about macro tests stored in `tests` keyword. It's an array of objects.

```json
{
  "result": "success",
  "tests": []
}
```

**Level 1**

- Macro test name/description stored under `test` keyword. It's an alphanumeric string.
- Macro test global result stored under `result` keyword. It accepts only `success` and `failure` values.
- Details about checks composing the macro test stored under `checks` keyword. It's an array of objects.

```json
{
  "test": "Checking the key type and size",
  "result": "success",
  "checks": []
}
```

**Level 2**

- Check name/description stored under `check` keyword. It's an alphanumeric string.
- Check result stored under `result` keyword. It accepts only `success` and `failure` values.
- Checked value stored under `value` keyword.

```json
{
  "check": "Keypair must be RSA",
  "result": "success",
  "value": "rsa"
}
```

**Full example**

```json
{
  "result": "success",
  "tests": [
    {
      "test": "Checking the key type and size",
      "result": "success",
      "checks": [
        {
          "check": "Keypair must be RSA",
          "result": "success",
          "value": "rsa"
        },
        {
          "check": "Key size must be one of [2048, 3072, 4096]",
          "result": "success",
          "value": "2048"
        },
      ] 
    },
  ]
}
```

**Comment by peppelinux** [comment]
I'd use only 0 and 2 level but feel free to implement all of them

**Comment by peppelinux** [comment]
Let's assume we have something like this 

````
{
  "test": {
    "that_level": {
      "metadata_strict": {
        "SpidSpMetadataCheck": [
          {
            "result": "success",
            "test": "SpidSpMetadataCheck.xsd_check"
          },
          {
            "result": "warning",
            "test": "The EntityID must be equal to http://localhost:8000/spid/metadata",
            "value": "http://localhost:8000/spid/metadata/"
          },
````

where `metadata_strict` is the test category and `SpidSpMetadataCheck` is the test class.
istead of having someother level we probably represent the statuses as part of the current structure, this way


````
{
  "test": {
    "status": {"result": "success", "test": [... list of tests ...], "value": []},
    "that_level": {
      "status": {"result": "success", "test": [... list of tests ...], "value": []},
      "metadata_strict": {
        "SpidSpMetadataCheck": [
          {
            "result": "success",
            "test": "SpidSpMetadataCheck.xsd_check"
          },
          {
            "result": "warning",
            "test": "The EntityID must be equal to http://localhost:8000/spid/metadata",
            "value": "http://localhost:8000/spid/metadata/"
          },
````

if some tests failes, value could include them

**Comment by psmiraglia** [comment]
**Note:** I'm not sure I really got your question/comment... :thinking: 

> Let's assume we have something like this
> 
> ```
> {
>   "test": {
>     "that_level": {
>       "metadata_strict": {
>         "SpidSpMetadataCheck": [
>           {
>             "result": "success",
>             "test": "SpidSpMetadataCheck.xsd_check"
>           },
>           {
>             "result": "warning",
>             "test": "The EntityID must be equal to http://localhost:8000/spid/metadata",
>             "value": "http://localhost:8000/spid/metadata/"
>           },
> ```
> 
> where `metadata_strict` is the test category and `SpidSpMetadataCheck` is the test class.

I think `that_level` level could be removed because `metadata_strict` category can be considered a brother of report produced by `spid-compliant-certificates`.

```json
{
  "test": {
    "metadata_strict": { ... },
    "cert_avviso_29": {
      "result": "success",
      "tests": [
        {
          "test": "Checking the key type and size",
          "result": "success",
          "checks": [
            {
              "check": "Keypair must be RSA",
              "result": "success",
              "value": "rsa"
            },
            {
              "check": "Key size must be one of [2048, 3072, 4096]",
              "result": "success",
              "value": "2048"
            },
          ] 
        },
      ]
    }
  }
}
```
> istead of having someother level we probably represent the statuses as part of the current structure, this way
> 
> ```
> {
>   "test": {
>     "status": {"result": "success", "test": [... list of tests ...], "value": []},
>     "that_level": {
>       "status": {"result": "success", "test": [... list of tests ...], "value": []},
>       "metadata_strict": {
>         "SpidSpMetadataCheck": [
>           {
>             "result": "success",
>             "test": "SpidSpMetadataCheck.xsd_check"
>           },
>           {
>             "result": "warning",
>             "test": "The EntityID must be equal to http://localhost:8000/spid/metadata",
>             "value": "http://localhost:8000/spid/metadata/"
>           },
> ```

IMHO, each level should contain a `status` keyword even if this represents a redundant info. This should simplify the parsing of the report because all the evaluations were made by the tests.

For instance, if I'm interested only in the global result and not about possible causes of a failure, I'll get `test.result` without digging into the nested levels. Otherwise, if I want to show in my app all the tests that were executed, I can dig the json and iterate over all the leaves, which structured as follows.

```json
{
  "test": "The Answer to the Ultimate Question of Life, the Universe, and Everything",
  "result": "success",
  "value": 42
}
```

> if some tests failes, value could include them

I would always include `value` keyword. Just to avoid annoying `if "value" in check: do_something()`.

**Comment by peppelinux** [comment]
I'm ok with `"value": ""` and also with your approach, go ahead and thank you!

**Comment by psmiraglia** [comment]
FYI, find here an early draft of the JSON report feature

https://github.com/psmiraglia/spid-compliant-certificates-python/tree/feat/validation-report-as-json

Install the package form that branch and run the validator as usual. You should obtain something like that

```
$ spid-compliant-certificates validator --sector public

   _____ _____ _____ _____     _____                      _ _             _
  / ____|  __ \_   _|  __ \   / ____|                    | (_)           | |
 | (___ | |__) || | | |  | | | |     ___  _ __ ___  _ __ | |_  __ _ _ __ | |_
  \___ \|  ___/ | | | |  | | | |    / _ \| '_ ` _ \| '_ \| | |/ _` | '_ \| __|
  ____) | |    _| |_| |__| | | |___| (_) | | | | | | |_) | | | (_| | | | | |_
 |_____/|_|   |_____|_____/   \_____\___/|_| |_| |_| .__/|_|_|\__,_|_| |_|\__|
   _____          _   _  __ _           _          | |
  / ____|        | | (_)/ _(_)         | |         |_|
 | |     ___ _ __| |_ _| |_ _  ___ __ _| |_ ___  ___
 | |    / _ \ '__| __| |  _| |/ __/ _` | __/ _ \/ __|
 | |___|  __/ |  | |_| | | | | (_| (_| | ||  __/\__ \
  \_____\___|_|   \__|_|_| |_|\___\__,_|\__\___||___/  v0.1



[INFO ] Validating certificate crt.pem against public sector specifications
[INFO ] It is ok
[INFO ] { ... here the JSON report ... }
```

**Comment by peppelinux** [comment]
Great, Just two notes.

JSON should be optionally stored directly to a file OR It must be printed in stdout without any pylogging headers.

Printing in stdout would mean that only the JSON report MUST be printed, even the banner (Fancy as It Is, really cute) should not be printed (maybe an option to handle this).

That's only few cents that MUST not sound too much brain stressing. If this kind of behaviour doesn't fit your taste don't worry and feel free to do what you prefer with your project. You drive.

I can find a way or another to get It on my needs, Just Need to know what's your preferences on this issue and that's still fun for you 😎

**Comment by psmiraglia** [comment]
Sure! Bear in mind that this feature is still WIP...

Consider the current status just an intermediate step. The JSON dump on stdout is just a rapid way to show you what you'll get in the end (reasonsbly, saved to a file)...

**Comment by psmiraglia** [comment]
FYI, [this](https://github.com/psmiraglia/spid-compliant-certificates-python/commit/d5275ed75f66ed7680c2f52c9d6de40ba2f3deea) introduces `--out-form` and `--out-file` options for the`validator` mode.

```
$ spid-compliant-certificates validator --out-file report.json --out-form json
   _____ _____ _____ _____     _____                      _ _             _
  / ____|  __ \_   _|  __ \   / ____|                    | (_)           | |
 | (___ | |__) || | | |  | | | |     ___  _ __ ___  _ __ | |_  __ _ _ __ | |_
  \___ \|  ___/ | | | |  | | | |    / _ \| '_ ` _ \| '_ \| | |/ _` | '_ \| __|
  ____) | |    _| |_| |__| | | |___| (_) | | | | | | |_) | | | (_| | | | | |_
 |_____/|_|   |_____|_____/   \_____\___/|_| |_| |_| .__/|_|_|\__,_|_| |_|\__|
   _____          _   _  __ _           _          | |
  / ____|        | | (_)/ _(_)         | |         |_|
 | |     ___ _ __| |_ _| |_ _  ___ __ _| |_ ___  ___
 | |    / _ \ '__| __| |  _| |/ __/ _` | __/ _ \/ __|
 | |___|  __/ |  | |_| | | | | (_| (_| | ||  __/\__ \
  \_____\___|_|   \__|_|_| |_|\___\__,_|\__\___||___/  v0.1




[I] Validating certificate /path/to/crt.pem against public sector specifications
[I] Certificate /path/to/crt.pem matches the public sector specifications

[ . . . ]

[I] Saving report as JSON in /path/to/report.json

```
