### ISSUE TITLE
Define repository secrets

### ISSUE THREAD

**Issue by psmiraglia** [italia/spid-compliant-certificates-python#3]
**Is your feature request related to a problem? Please describe.**

In order to publish on [Docker Hub](https://hub.docker.com/) and [PyPI](https://pypi.org) some repository secrets should be created.

**Describe the solution you'd like**

Secrets to publish on Docker Hub

- `DOCKERHUB_USERNAME`
- `DOCKERHUB_TOKEN`
- `DOCKER_BASE_REPO` (realistically valued with `italia`)

Secrets to publish on PyPI

- `PYPI_API_TOKEN`

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by psmiraglia** [comment]
@peppelinux `PYPI_API_TOKEN` is ready. What about `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`?

**Comment by bfabio** [comment]
@psmiraglia I added the two DockerHub secrets

Can you please rename the token at the pypi.org side to be compliant with our internal token naming policy? "`github/italia/spid-compliant-certificates-python PYPI_API_TOKEN`" would do

**Comment by psmiraglia** [comment]
> @psmiraglia I added the two DockerHub secrets

👍 

> Can you please rename the token at the pypi.org side to be compliant with our internal token naming policy? "`github/italia/spid-compliant-certificates-python PYPI_API_TOKEN`" would do

My super powers are not enough. You should ask @peppelinux

**Comment by psmiraglia** [comment]
@bfabio @peppelinux some questions...

1. Could you please check the Docker Hub configuration? I re-executed the workflow that build and push docker images but, despite a [successful run](https://github.com/italia/spid-compliant-certificates-python/actions/runs/742737538), I can't see the image on [dockerhub/italia](https://hub.docker.com/u/italia).

2. Could you please send me (in private) the value of `DOCKERHUB_USERNAME`?

2. Was the repository [`italia/spid-compliant-certificates-python`](https://hub.docker.com/r/italia/spid-compliant-certificates-python) manually created? If so, I would ask you to rename it in `italia/spid-compliant-certificates`. Differentiation between `python` and `shell` will be made with the image versions (e.g. `0.1-python`, `7.2-shell`)

**Comment by bfabio** [comment]
@psmiraglia 

> 2. Could you please send me (in private) the value of `DOCKERHUB_USERNAME`?

[This line](https://github.com/italia/spid-compliant-certificates-python/blob/69550d19d0b6255a6c694dde5976881ad51aba96/.github/workflows/docker.yml#L47) should read ` italia/spid-compliant-certificates`, as `italia` is an org and our username is different.
 
> 3. Was the repository [`italia/spid-compliant-certificates-python`](https://hub.docker.com/r/italia/spid-compliant-certificates-python) manually created? If so, I would ask you to rename it in `italia/spid-compliant-certificates`. Differentiation between `python` and `shell` will be made with the image versions (e.g. `0.1-python`, `7.2-shell`)

It was, I created it earlier this morning, but it wasn't really needed and I can remove it.

Maybe I missing something, but If I can have my say on this, it seems kinda weird that two separate GitHub repos push to the same DockerHub image under a different tag.
As a user I would expect `github.com/italia/foobar` to build `italia/foobar` on DockerHub.

**Comment by psmiraglia** [comment]
> [This line](https://github.com/italia/spid-compliant-certificates-python/blob/69550d19d0b6255a6c694dde5976881ad51aba96/.github/workflows/docker.yml#L47) should read ` italia/spid-compliant-certificates`, as `italia` is an org and our username is different.

Ok. I'm going to fix the workflow...

> It was, I created it earlier this morning, but it wasn't really needed and I can remove it.

Ok

> Maybe I missing something, but If I can have my say on this, it seems kinda weird that two separate GitHub repos push to the same DockerHub image under a different tag. As a user I would expect `github.com/italia/foobar` to build `italia/foobar` on DockerHub. 

IMHO, the shell version of the tool does not really require a Docker image because it uses standard and very common shell commands.

@bfabio @peppelinux: If you agree with me, we could have only `italia/spid-compliant-certificates` Docker image, which is fueled by  `github/italia/spid-compliant-certificates-python`.

**Comment by peppelinux** [comment]
Ok pypi Token updated with name "github/italia/spid-compliant-certificates-python PYPI_API_TOKEN" and also here, in project settings

**Comment by psmiraglia** [comment]
> Ok. I'm going to fix the workflow...

#14 #15

**Comment by bfabio** [comment]
> @bfabio @peppelinux: If you agree with me, we could have only `italia/spid-compliant-certificates` Docker image, which is fueled by `github/italia/spid-compliant-certificates-python`.

It should be `italia/spid-compliant-certificates-python` on DockerHub, IMO

**Comment by psmiraglia** [comment]
> It should be `italia/spid-compliant-certificates-python` on DockerHub, IMO

I think if we use `-python`, we indirectly say *"we have Python and other languages images"*. This is why I would exclude `-python` from the image name.

**Comment by bfabio** [comment]
On the other end we'd have https://github.com/italia/spid-compliant-certificates with no relation with https://hub.docker.com/r/italia/spid-compliant-certificates, despite the name. That'd be pretty surprising, but I don't want to interject more than necessary and be blocking on this, so I'll trust your judgment guys :)

**Comment by psmiraglia** [comment]
@bfabio If you don't want to be blocking, review/approve #16 and create `DOCKER_BASE_REPO` secret! Hey you @peppelinux, where are you going? This is valid also for you... :stuck_out_tongue: :smile: 

Jokes apart guys, take your time! About value for `DOCKER_BASE_REPO`, it should be clear. If not, ping me in private. You both know where I am...
