### ISSUE TITLE
Validation and Report: Specializing functions by features

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-compliant-certificates-python#36]
Hi Paolo, 
I found this here
https://github.com/italia/spid-compliant-certificates-python/blob/8e23adfd7cbb1e088f3143dc5a7e2d33607f3ad3/spid_compliant_certificates/validator/validate.py#L46

It seems to me that the report have been embedded in the validation function.
The behaviour I've got is that if I execute the validate function it will trigger the report (that print out on stderr things).

I'm wondering if it could be better to have a validation function that simply returns a result object and this latter would be then handled by the Report system, in a second moment?

The exit strategy for me would be parsing directly the json file, where report system wrote things, at the same time, I'm wondering if this issue could be helpful for you, in a special manner I mean, regarding design and way-to-do-things

thank you, this tool is awesome

**Comment by psmiraglia** [comment]
> It seems to me that the report have been embedded in the validation function.
The behaviour I've got is that if I execute the validate function it will trigger the report (that print out on stderr things).

Mmm... it should not... Could you please share what you're seeing?

> I'm wondering if it could be better to have a validation function that simply returns a result object and this latter would be then handled by the Report system, in a second moment?

The `validate` function returns an instance of [`Report`](https://github.com/italia/spid-compliant-certificates-python/blob/8e23adfd7cbb1e088f3143dc5a7e2d33607f3ad3/spid_compliant_certificates/validator/report.py#L81), which can be successively serialized as JSON, XML, YAML or TXT with [`ReportSerialzier`](https://github.com/italia/spid-compliant-certificates-python/blob/8e23adfd7cbb1e088f3143dc5a7e2d33607f3ad3/spid_compliant_certificates/validator/report.py#L104). For instance...

```python
r = validate(...)
rs = ReportSerializer()
with open('report.json', 'wb') as fp:
    fp.write(rs.serialize(r, 'json').encode())
    fp.close()
```

If you want to manage the report programmatically (e.g. in your code), you can use the [`as_dict()`](https://github.com/italia/spid-compliant-certificates-python/blob/8e23adfd7cbb1e088f3143dc5a7e2d33607f3ad3/spid_compliant_certificates/validator/report.py#L93-L98) method. For instance...

```python

r = validate(...)
for k in r.as_dict():
   ... do something ...
```

Here a real example

https://github.com/italia/spid-compliant-certificates-python/blob/8e23adfd7cbb1e088f3143dc5a7e2d33607f3ad3/bin/spid-compliant-certificates#L261-L285

> The exit strategy for me would be parsing directly the json file, where report system wrote things, at the same time, I'm wondering if this issue could be helpful for you, in a special manner I mean, regarding design and way-to-do-things

Appreciated

> thank you, this tool is awesome

:cupid:

**Comment by peppelinux** [comment]
validate(...) prints out the report in stdout
