### ISSUE TITLE
spid-compliant-certificates is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by mperu92** [italia/spid-compliant-certificates-python#64]
**Topic**

'spid-compliant-certificates' is not recognized as an internal or external command,

**Question**

I have installed 'spid-compliant-certificates' in all the two ways:

```
pip install spid-compliant-certificates
```
and
```
pip install -r requirements.txt
python setup.py install
```
it install the package correctly, but when i try to launch it:

```
spid-compliant-certificates generator ...etc
```
or
```
py -m spid-compliant-certificates generator ...etc
```
it says:
```
C:\Users\[user]\AppData\Local\Programs\Python\Python39\python.exe: No module named spid-compliant-certificates
```

what i have to do to launch the commands in my command prompt?
Thank you

**Comment by peppelinux** [comment]
please do a `pip list` to see if the package has been installed correctly

if you continue to have problems I would suggest you to use the Docker image

**Comment by mperu92** [comment]
Unfortunately it's present in the pip packages list:
![image](https://user-images.githubusercontent.com/38279865/127674118-9ed9bc35-2ac0-46c0-b66f-528522e7e824.png)

i will try with the Docker image

**Comment by mperu92** [comment]
I used Docker and it actually went better.
If i launch the command 
```
docker run -ti --rm -v "/tmp/certs" local/spid-compliant-certificates generator --key-size 3072 --common-name "A.C.M.E" --days 365 --entity-id https://spid.acme.it --locality-name Roma --org-id "PA:IT-c_h501" --org-name "A Company Making Everything" --sector public
```
it works fine
![image](https://user-images.githubusercontent.com/38279865/127826721-cd13da36-cf30-4319-a579-9e9116a9a5f9.png)

But when i launch the validation command:
```
docker run -ti --rm -v "/tmp/certs" local/spid-compliant-certificates validator --sector public
```
it says unable to find certificate:
![image](https://user-images.githubusercontent.com/38279865/127826984-e4fcddab-492b-4120-a25d-2a110c6d5a0c.png)

am I doing something wrong in launching the second command?

Thank you!

**Comment by peppelinux** [comment]
Use the path of the crt you're going to validate, it must be placed in the Docker volume and its path must be included in the validation command

**Comment by mperu92** [comment]
Thank you. Creating a docker volume and then generate the cert into this then validate it worked fine!
Thank you!
